version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.CrmSdk.CoreAssemblies
    versions:
    - 9.0.2.29
    - 9.0.2.32
  - dependency-name: Microsoft.CrmSdk.Workflow
    versions:
    - 9.0.2.29
    - 9.0.2.32
